### ISSUE TITLE
Go 1.16: panic: reflect: Call using sweet.testDeps as type testing.testDeps

### ISSUE THREAD

**Issue by eclipseo** [aphistic/sweet#17]
On Fedora Rawhide with Golang 1.16 beta 1, I get the following error running go test:

```
Testing    in: /builddir/build/BUILD/sweet-0.3.0/_build/src
         PATH: /builddir/build/BUILD/sweet-0.3.0/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/sweet-0.3.0/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags " -X github.com/aphistic/sweet/version=0.3.0 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  '"
      testing: github.com/aphistic/sweet
github.com/aphistic/sweet
panic: reflect: Call using sweet.testDeps as type testing.testDeps
goroutine 1 [running]:
reflect.Value.call(0x5590e8fe3fe0, 0x5590e9025b40, 0x13, 0x5590e8e4a783, 0x4, 0xc00006c6c0, 0x4, 0x4, 0xc0001b1830, 0x5590e8c154df, ...)
	/usr/lib/golang/src/reflect/value.go:406 +0x1317
reflect.Value.Call(0x5590e8fe3fe0, 0x5590e9025b40, 0x13, 0xc00006c6c0, 0x4, 0x4, 0x2, 0x4, 0x40)
	/usr/lib/golang/src/reflect/value.go:337 +0xb9
github.com/aphistic/sweet.mainStart(0xc00006ac00, 0x5590e902eac8, 0xc0000572f0, 0x5590e926bb00)
	/builddir/build/BUILD/sweet-0.3.0/_build/src/github.com/aphistic/sweet/gotest_integration.go:45 +0x617
github.com/aphistic/sweet.Run(0xc000198180, 0x5590e90252d0)
	/builddir/build/BUILD/sweet-0.3.0/_build/src/github.com/aphistic/sweet/runner.go:86 +0x1bf
github.com/aphistic/sweet.TestMain(0xc000198180)
	/builddir/build/BUILD/sweet-0.3.0/_build/src/github.com/aphistic/sweet/sweet_test.go:18 +0x85
main.main()
	_testmain.go:43 +0x165
exit status 2
FAIL	github.com/aphistic/sweet	0.008s
```

**Comment by eclipseo** [comment]
This is due to this change: https://github.com/golang/go/commit/4f76fe86756841befb6574ce4bf04113d14389d4#diff-36f401ff1ffadb7d7a39cf41c2329615b159fa95cf2e14c1f58d8c46331af429

where
```
// SetPanicOnExit0 tells the os package whether to panic on os.Exit(0).
func (TestDeps) SetPanicOnExit0(v bool) {
	testlog.SetPanicOnExit0(v)
}
```
was added.
