### ISSUE TITLE
Catch assertions in goroutines

### ISSUE THREAD

**Issue by efritz** [aphistic/sweet#6]
Currently, it seems that sweet panics when an assertion failure occurs in a goroutine.

```go
go func() {
	defer close(sync)

	err := server.Subscribe(&proto.SubscribeRequest{}, subscribeServer)
	Expect(err).To(BeNil())
}()
```

An example error:

```
panic: (*sweet.testFailure) (0x8b0ec0,0xc420153b90)

goroutine 8 [running]:
panic(0x8b0ec0, 0xc420153b90)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
<anon-project>vendor/github.com/aphistic/sweet.GomegaFail(0xc420087100, 0x77, 0xc420155840, 0x1, 0x1)
	/home/efritz/go/src/<anon-project>vendor/github.com/aphistic/sweet/failures.go:31 +0xc4
<anon-project>vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc420226640, 0xc446c0, 0xc87588, 0x1, 0x0, 0x0, 0x0, 0xc87588)
	/home/efritz/go/src/<anon-project>vendor/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x1ed
<anon-project>vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc420226640, 0xc446c0, 0xc87588, 0x0, 0x0, 0x0, 0xc420226640)
	/home/efritz/go/src/<anon-project>vendor/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xae
<anon-project>server.(*HandlersSuite).TestOnlyOneConcurrentSubscriberAllowed.func1(0xc420248000, 0xc420156e70, 0xc42002e240)
	/home/efritz/go/src/<anon-project>server/handlers_test.go:60 +0x12d
created by <anon-project>server.(*HandlersSuite).TestOnlyOneConcurrentSubscriberAllowed
	/home/efritz/go/src/<anon-project>server/handlers_test.go:61 +0x324
exit status 2
FAIL	<anon-project>	0.007s
```

**Comment by aphistic** [comment]
I did some looking into this and I can definitely reproduce it but I'm not sure if it's something in sweet or gomega that's causing it.  I think it might be gomega failing to capture a panic and notifying sweet correctly but it could also be something weird in the way panic/recover is handled in nested goroutines.
